services:
  - type: web
    name: quotex-ai-v7
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TWELVE_DATA_API_KEY
        sync: false
